import "server-only";

import { createAdminClient } from "@/lib/supabase/admin";
import { hashToken } from "@/lib/envelopes/tokens";
import { embedOne } from "@/lib/supabase/embed";
import type { FieldType, Routing, SignerField } from "@/lib/envelopes/types";

/**
 * Resolving a signer token.
 *
 * This is the authorization boundary for unauthenticated signing. A signer has
 * no database identity, so every check happens here and the caller is handed
 * only the rows the token proves it may touch.
 *
 * Refusals are deliberately indistinguishable from the outside: expired, wrong,
 * already-signed and not-your-turn all present the same way to anyone probing,
 * while the owner's audit trail records what really happened.
 */
export type SignerContext = {
  recipient: {
    id: string;
    name: string;
    email: string;
    role: string | null;
    status: string;
    consentedAt: string | null;
  };
  envelope: {
    id: string;
    contractId: string;
    sourceVersionId: string;
    routing: Routing;
    status: string;
    message: string | null;
    expiresAt: string | null;
  };
  document: {
    title: string;
    pageCount: number;
    sha256: string | null;
  };
  fields: SignerField[];
};

export type SignerLookup =
  | { ok: true; context: SignerContext }
  | { ok: false; reason: "invalid" | "expired" | "done" | "declined" | "waiting" | "voided" };

export async function resolveSignerToken(token: string): Promise<SignerLookup> {
  if (!token || token.length < 20 || token.length > 200) return { ok: false, reason: "invalid" };

  let tokenHash: string;
  try {
    tokenHash = hashToken(token);
  } catch (err) {
    // A missing pepper is a deployment fault, not a bad link. Log it loudly and
    // refuse rather than letting anyone in.
    console.error("signer_pepper_missing", err);
    return { ok: false, reason: "invalid" };
  }

  const admin = createAdminClient();

  const { data: recipient, error } = await admin
    .from("recipients")
    .select(
      `id, name, email, role, status, consented_at, token_expires_at, envelope_id,
       envelopes (
         id, contract_id, source_version_id, routing, status, message, expires_at,
         contracts ( title )
       )`,
    )
    .eq("token_hash", tokenHash)
    .maybeSingle();

  if (error || !recipient) return { ok: false, reason: "invalid" };

  const envelope = embedOne(recipient.envelopes) as unknown as {
    id: string;
    contract_id: string;
    source_version_id: string;
    routing: Routing;
    status: string;
    message: string | null;
    expires_at: string | null;
    contracts: { title: string } | { title: string }[] | null;
  } | null;

  if (!envelope) return { ok: false, reason: "invalid" };

  if (envelope.status === "voided") return { ok: false, reason: "voided" };
  if (recipient.status === "declined") return { ok: false, reason: "declined" };
  if (recipient.status === "signed") return { ok: false, reason: "done" };
  if (envelope.status === "completed") return { ok: false, reason: "done" };

  const expiry = recipient.token_expires_at ?? envelope.expires_at;
  if (expiry && new Date(expiry).getTime() < Date.now()) {
    return { ok: false, reason: "expired" };
  }

  if (envelope.status !== "sent" && envelope.status !== "partially_signed") {
    return { ok: false, reason: "invalid" };
  }

  // Sequential routing: everyone before this recipient must have signed.
  if (envelope.routing === "sequential") {
    const ready = await isRecipientsTurn(envelope.id, recipient.id);
    if (!ready) return { ok: false, reason: "waiting" };
  }

  // Fetched separately rather than embedded: envelopes has two foreign keys
  // into contract_versions (source and final), so an embed would have to name
  // the constraint, and that name is generated by Postgres.
  const { data: sourceVersion } = await admin
    .from("contract_versions")
    .select("page_count, sha256")
    .eq("id", envelope.source_version_id)
    .maybeSingle();

  const { data: fields } = await admin
    .from("fields")
    .select(
      "id, type, page, x, y, w, h, required, label, value_text, value_bool, value_asset_path, filled_at, order_index",
    )
    .eq("recipient_id", recipient.id)
    .order("page", { ascending: true })
    .order("order_index", { ascending: true });

  return {
    ok: true,
    context: {
      recipient: {
        id: recipient.id,
        name: recipient.name,
        email: recipient.email,
        role: recipient.role,
        status: recipient.status,
        consentedAt: recipient.consented_at,
      },
      envelope: {
        id: envelope.id,
        contractId: envelope.contract_id,
        sourceVersionId: envelope.source_version_id,
        routing: envelope.routing,
        status: envelope.status,
        message: envelope.message,
        expiresAt: envelope.expires_at,
      },
      document: {
        title: embedOne<{ title: string }>(envelope.contracts as unknown)?.title ?? "Document",
        pageCount: sourceVersion?.page_count ?? 1,
        sha256: sourceVersion?.sha256 ?? null,
      },
      fields: ((fields ?? []) as (SignerField & { order_index: number })[]).map(
        ({ order_index: _order, ...field }) => field,
      ),
    },
  };
}

/** True when every earlier recipient in a sequential envelope has signed. */
export async function isRecipientsTurn(
  envelopeId: string,
  recipientId: string,
): Promise<boolean> {
  const admin = createAdminClient();

  const { data: rows } = await admin
    .from("recipients")
    .select("id, order_index, status")
    .eq("envelope_id", envelopeId)
    .order("order_index", { ascending: true });

  const list = (rows ?? []) as { id: string; order_index: number; status: string }[];
  const self = list.find((row) => row.id === recipientId);
  if (!self) return false;

  return list
    .filter((row) => row.order_index < self.order_index)
    .every((row) => row.status === "signed");
}

/** The next recipient who still needs notifying in a sequential envelope. */
export async function nextSequentialRecipient(
  envelopeId: string,
): Promise<{ id: string; name: string; email: string } | null> {
  const admin = createAdminClient();

  const { data: rows } = await admin
    .from("recipients")
    .select("id, name, email, order_index, status")
    .eq("envelope_id", envelopeId)
    .order("order_index", { ascending: true });

  const list = (rows ?? []) as {
    id: string;
    name: string;
    email: string;
    order_index: number;
    status: string;
  }[];

  const next = list.find((row) => row.status !== "signed" && row.status !== "declined");
  return next ? { id: next.id, name: next.name, email: next.email } : null;
}

/** Field types that a signer fills with an image rather than text. */
export function isImageField(type: FieldType): boolean {
  return type === "signature" || type === "initials";
}
